// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Cpr.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AddressInfromation
    {
        /// <summary>
        /// Initializes a new instance of the AddressInfromation class.
        /// </summary>
        public AddressInfromation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AddressInfromation class.
        /// </summary>
        public AddressInfromation(AddressPrivate address = default(AddressPrivate), string status = default(string), System.DateTime? efectFrom = default(System.DateTime?), bool? effectFromUncertaintyMarking = default(bool?))
        {
            Address = address;
            Status = status;
            EfectFrom = efectFrom;
            EffectFromUncertaintyMarking = effectFromUncertaintyMarking;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public AddressPrivate Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "efectFrom")]
        public System.DateTime? EfectFrom { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "effectFromUncertaintyMarking")]
        public bool? EffectFromUncertaintyMarking { get; set; }

    }
}
