// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Cpr.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DepartureAndEntry
    {
        /// <summary>
        /// Initializes a new instance of the DepartureAndEntry class.
        /// </summary>
        public DepartureAndEntry()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DepartureAndEntry class.
        /// </summary>
        public DepartureAndEntry(string countryCodeEntry = default(string), string countryCodeDeparture = default(string), string landEntry = default(string), string landDeparture = default(string), string status = default(string), System.DateTime? effectFrom = default(System.DateTime?), bool? effectFromUncertaintyMarking = default(bool?), SimpleAddress foreignAddress = default(SimpleAddress))
        {
            CountryCodeEntry = countryCodeEntry;
            CountryCodeDeparture = countryCodeDeparture;
            LandEntry = landEntry;
            LandDeparture = landDeparture;
            Status = status;
            EffectFrom = effectFrom;
            EffectFromUncertaintyMarking = effectFromUncertaintyMarking;
            ForeignAddress = foreignAddress;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "countryCodeEntry")]
        public string CountryCodeEntry { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "countryCodeDeparture")]
        public string CountryCodeDeparture { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "landEntry")]
        public string LandEntry { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "landDeparture")]
        public string LandDeparture { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "effectFrom")]
        public System.DateTime? EffectFrom { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "effectFromUncertaintyMarking")]
        public bool? EffectFromUncertaintyMarking { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "foreignAddress")]
        public SimpleAddress ForeignAddress { get; set; }

    }
}
