// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Cpr.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LegalGuardianPrivate
    {
        /// <summary>
        /// Initializes a new instance of the LegalGuardianPrivate class.
        /// </summary>
        public LegalGuardianPrivate()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LegalGuardianPrivate class.
        /// </summary>
        public LegalGuardianPrivate(string name = default(string), SimpleAddress simpleAddress = default(SimpleAddress))
        {
            Name = name;
            SimpleAddress = simpleAddress;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "simpleAddress")]
        public SimpleAddress SimpleAddress { get; set; }

    }
}
