// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Cpr.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SimpleAddress
    {
        /// <summary>
        /// Initializes a new instance of the SimpleAddress class.
        /// </summary>
        public SimpleAddress()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SimpleAddress class.
        /// </summary>
        public SimpleAddress(string addressLine1 = default(string), string addressLine2 = default(string), string addressLine3 = default(string), string addressLine4 = default(string), string addressLine5 = default(string))
        {
            AddressLine1 = addressLine1;
            AddressLine2 = addressLine2;
            AddressLine3 = addressLine3;
            AddressLine4 = addressLine4;
            AddressLine5 = addressLine5;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "addressLine1")]
        public string AddressLine1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "addressLine2")]
        public string AddressLine2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "addressLine3")]
        public string AddressLine3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "addressLine4")]
        public string AddressLine4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "addressLine5")]
        public string AddressLine5 { get; set; }

    }
}
